;;; init.el ---                       -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(push (expand-file-name "lisp" user-emacs-directory) load-path)
(require 'init-package)
;; (require 'benchmark-init)
(require 'init-utils)
(when-macos (require 'init-macos))
(when-linux (require 'init-linux))
(require 'init-editor)
(require 'init-swiper)
(require 'init-themes)
(require 'init-erlang)
(require 'init-magit)
(require 'init-company)
(require 'init-docker)
(require 'init-latex)
(require 'init-lisp)
(require 'init-lua)
(require 'init-markdown)
(require 'init-modeline)
(require 'init-orgmode)
(require 'init-project)
(require 'init-rectangle)
(require 'init-snippet)
(require 'init-switch-window)
(require 'init-translate)
(require 'init-undotree)
(require 'init-webmode)
(require 'init-whichkey)
(require 'init-network)
(require 'init-golang)
(require 'init-yaml)

(provide 'init)
;;; init.el ends here
